# Generated by Django 3.1.7 on 2021-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caloric_content',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
