# Generated by Django 3.1.7 on 2021-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210423_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='date',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
    ]
