# Generated by Django 3.1.7 on 2021-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
