# Generated by Django 3.1.7 on 2021-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=250)),
                ('section', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date_published')),
            ],
        ),
    ]
