# Generated by Django 3.1.7 on 2021-04-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210411_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.section'),
        ),
    ]
